version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db

  db:
    image: mariadb:11.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./mysql:/var/lib/mysql